### PR TITLE
Transfer learning

### PR DESCRIPTION
**Pull request by wagenrace**

### CODE REVIEW

**Comment by gwaygenomics** [comment]
Another thing that you'll prob want to fix in the future is to correctly associate your account to your commits

image

You probably just need to set a global git username on your machine. https://docs.github.com/en/github/using-git/setting-your-username-in-git

**Comment by wagenrace** [comment]
> 
> 
> Another thing that you'll prob want to fix in the future is to correctly associate your account to your commits
> 
> image
> 
> You probably just need to set a global git username on your machine. https://docs.github.com/en/github/using-git/setting-your-username-in-git

I will look into it again, but it is a problem because I have 2 different git accounts connected

**Comment by pamzgt** [comment]
Hi @wagenrace , 

I think I can not access the review request because you deleted the branch. So I give you my feed back here.

### general remarks
- Very nice and easy to follow examples. Cool that you included a biological dataset
-  I would recommend to keep the frozen layers notebook (you mentioned via email that you might not keep it), otherwise it might become too basic. I think that the complete thing is a good amount of information for one training. 

Here are some recommendations to improve the contents

For all notebooks
-	Fix the ylim for all plots, for an easier visual comparison between the different models
-	Add markdown cells between the training experiments with a short comment on what is being done (without-pretraining, with pre-training, 4 frozen layers, etc) 
-	Add a markdown cell with title “data generation” for the datagenerators

For Readme:
-	I think it would be nice to explain the two transfer learning concepts you use in the notebooks (ta least from my point of view) :  
 -  fine-tuning:  re-train the full model using the pre-trained weights for parameter initialization (imagenet_to_food101.ipynb, imagenet_to_malaria_blood_cells.ipynb)
 -  feature extraction transfer: keep pre-trained weights from a subset of hidden layers while re-training output layer weights (frozen_layers.ipynb) 

Frozen layers
-	The first two figure titles “without pre-training” are misleading. What I understood, is that all models are pre-trained (weights="imagenet"). Maybe change “without pre-training” for  “4 frozen blocks”,” 8 frozen blocks”, etc

**Comment by wagenrace** [comment]
@pamzgt thank you for your feedback this is very use full. I start working on it directly.
Sorry I moved the branches I am working on to my own forked project to keep it clean.
If you could help me with the typos/grammar that would be awesome! I really could use the help.
I make a new pull request from my personal repo once I finished with you feedback

**Pull request merged**
